"use client";

import { useMemo, useState } from "react";
import type { Dispatch, SetStateAction } from "react";
import type { PlaybookVersion, ProducerQueueTask, ProducerTaskType } from "@/lib/producer/mock-queue";

type QueueFilter = "All" | ProducerTaskType;
type PhaseFilter = "All" | "Danger Zone" | "The Plateau";
type SortColumn = "studentName" | "triggerLesson" | "taskName" | "createdAt";
type ProducerQueueViewProps = {
  tasks: ProducerQueueTask[];
  setTasks: Dispatch<SetStateAction<ProducerQueueTask[]>>;
  playbookVersion: PlaybookVersion;
  setPlaybookVersion: Dispatch<SetStateAction<PlaybookVersion>>;
  playbookVersions: PlaybookVersion[];
};

function getPhase(triggerLesson: number): "Danger Zone" | "The Plateau" {
  return triggerLesson <= 15 ? "Danger Zone" : "The Plateau";
}

function timeAgo(iso: string) {
  const ms = Date.now() - new Date(iso).getTime();
  const min = Math.floor(ms / 60000);
  if (min < 1) return "Just now";
  if (min < 60) return `${min} min ago`;
  const hr = Math.floor(min / 60);
  if (hr < 24) return `${hr} hr ago`;
  return `${Math.floor(hr / 24)} day${hr >= 48 ? "s" : ""} ago`;
}

export function ProducerQueueView({
  tasks,
  setTasks,
  playbookVersion,
  setPlaybookVersion,
  playbookVersions,
}: ProducerQueueViewProps) {
  const [taskFilter, setTaskFilter] = useState<QueueFilter>("All");
  const [phaseFilter, setPhaseFilter] = useState<PhaseFilter>("All");
  const [sortColumn, setSortColumn] = useState<SortColumn>("createdAt");
  const [ascending, setAscending] = useState(true);
  const [activeTask, setActiveTask] = useState<ProducerQueueTask | null>(null);

  const filtered = useMemo(() => {
    let rows = tasks.filter((task) => task.playbookVersion === playbookVersion);
    if (taskFilter !== "All") rows = rows.filter((task) => task.taskType === taskFilter);
    if (phaseFilter !== "All") rows = rows.filter((task) => getPhase(task.triggerLesson) === phaseFilter);
    return [...rows].sort((a, b) => {
      const getValue = (task: ProducerQueueTask) => {
        if (sortColumn === "createdAt") return new Date(task.createdAt).getTime();
        if (sortColumn === "triggerLesson") return task.triggerLesson;
        return task[sortColumn].toLowerCase();
      };
      const va = getValue(a);
      const vb = getValue(b);
      if (va < vb) return ascending ? -1 : 1;
      if (va > vb) return ascending ? 1 : -1;
      return 0;
    });
  }, [tasks, playbookVersion, taskFilter, phaseFilter, sortColumn, ascending]);

  const counts = useMemo(() => {
    const base = tasks.filter((task) => task.playbookVersion === playbookVersion);
    return {
      all: base.length,
      media: base.filter((task) => task.taskType === "Media Upload").length,
      comms: base.filter((task) => task.taskType === "In-Room Milestone").length,
      alerts: base.filter((task) => task.taskType === "System Action").length,
      danger: base.filter((task) => getPhase(task.triggerLesson) === "Danger Zone").length,
      plateau: base.filter((task) => getPhase(task.triggerLesson) === "The Plateau").length,
    };
  }, [tasks, playbookVersion]);

  const onSort = (column: SortColumn) => {
    if (column === sortColumn) setAscending((value) => !value);
    else {
      setSortColumn(column);
      setAscending(true);
    }
  };

  const markComplete = (taskId: string) => {
    setTasks((current) => current.filter((task) => task.taskId !== taskId));
    setActiveTask(null);
  };

  const syncPlaybookRules = () => {
    const nextTask: ProducerQueueTask = {
      taskId: `q-${Date.now()}`,
      studentName: "New Queue Student",
      age: 13,
      instrument: "Violin",
      triggerLesson: 7,
      taskName: "Auto-generated Queue Task",
      taskType: "System Action",
      opsInstructions: "This was generated by scaffold sync to simulate engine output.",
      parentName: "Parent Contact",
      parentEmail: "parent@example.com",
      createdAt: new Date().toISOString(),
      playbookVersion,
    };
    setTasks((current) => [nextTask, ...current]);
  };

  return (
    <section className="card">
      <div className="card-header">
        <div>
          <div className="card-title">Daily Action Queue</div>
          <div className="section-sub">Review milestones, communications, and alert actions for the active playbook.</div>
        </div>
        <div className="flex items-center gap-2">
          <select className="inp" value={playbookVersion} onChange={(event) => setPlaybookVersion(event.target.value as PlaybookVersion)}>
            {playbookVersions.map((version) => (
              <option key={version} value={version}>
                {version}
              </option>
            ))}
          </select>
          <button type="button" className="btn btn-primary" onClick={syncPlaybookRules}>
            Sync Playbook Rules
          </button>
        </div>
      </div>
      <div className="tabs">
        <button type="button" className={`tab ${taskFilter === "All" ? "active" : ""}`} onClick={() => setTaskFilter("All")}>
          All Tasks ({counts.all})
        </button>
        <button
          type="button"
          className={`tab ${taskFilter === "Media Upload" ? "active" : ""}`}
          onClick={() => setTaskFilter("Media Upload")}
        >
          Media ({counts.media})
        </button>
        <button
          type="button"
          className={`tab ${taskFilter === "In-Room Milestone" ? "active" : ""}`}
          onClick={() => setTaskFilter("In-Room Milestone")}
        >
          Comms ({counts.comms})
        </button>
        <button
          type="button"
          className={`tab ${taskFilter === "System Action" ? "active" : ""}`}
          onClick={() => setTaskFilter("System Action")}
        >
          Alerts ({counts.alerts})
        </button>
      </div>
      <div className="tabs">
        <button type="button" className={`tab ${phaseFilter === "All" ? "active" : ""}`} onClick={() => setPhaseFilter("All")}>
          All Phases
        </button>
        <button
          type="button"
          className={`tab ${phaseFilter === "Danger Zone" ? "active" : ""}`}
          onClick={() => setPhaseFilter("Danger Zone")}
        >
          Danger Zone ({counts.danger})
        </button>
        <button
          type="button"
          className={`tab ${phaseFilter === "The Plateau" ? "active" : ""}`}
          onClick={() => setPhaseFilter("The Plateau")}
        >
          Plateau ({counts.plateau})
        </button>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead>
            <tr className="border-b border-white/10 text-xs uppercase tracking-wider text-slate-400">
              <th className="py-3">
                <button type="button" onClick={() => onSort("studentName")} className="font-bold">
                  Student
                </button>
              </th>
              <th className="py-3">
                <button type="button" onClick={() => onSort("triggerLesson")} className="font-bold">
                  Trigger
                </button>
              </th>
              <th className="py-3">
                <button type="button" onClick={() => onSort("taskName")} className="font-bold">
                  Required Action
                </button>
              </th>
              <th className="py-3">
                <button type="button" onClick={() => onSort("createdAt")} className="font-bold">
                  Time in Queue
                </button>
              </th>
              <th className="py-3 text-right">Execute</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((task) => (
              <tr key={task.taskId} className="border-b border-white/5">
                <td className="py-3">
                  <div className="font-semibold">{task.studentName}</div>
                  <div className="text-xs text-slate-400">{task.age}y • {task.instrument}</div>
                </td>
                <td className="py-3">
                  <span className="badge b-cyan">Lesson {task.triggerLesson}</span>
                </td>
                <td className="py-3">
                  <div className="font-semibold">{task.taskName}</div>
                  <div className="text-xs text-slate-400">{task.taskType} • {getPhase(task.triggerLesson)}</div>
                </td>
                <td className="py-3 text-xs text-slate-400">{timeAgo(task.createdAt)}</td>
                <td className="py-3 text-right">
                  <button type="button" className="btn btn-sm" onClick={() => setActiveTask(task)}>
                    Review
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {!filtered.length ? <p className="empty-copy">No queue tasks match the selected filters.</p> : null}

      {activeTask ? (
        <div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/70 p-4">
          <div className="card max-h-[90vh] w-full max-w-3xl overflow-y-auto">
            <div className="card-header">
              <div>
                <div className="card-title">{activeTask.studentName}</div>
                <div className="section-sub">
                  Lesson {activeTask.triggerLesson} • {activeTask.taskName}
                </div>
              </div>
              <button type="button" className="btn btn-sm" onClick={() => setActiveTask(null)}>
                Close
              </button>
            </div>
            <div className="space-y-3">
              <div className="rounded-xl border border-white/10 bg-black/10 p-3">
                <div className="text-xs uppercase tracking-wider text-slate-400">Playbook Instruction</div>
                <p className="mt-1 text-sm">{activeTask.opsInstructions}</p>
              </div>
              <div className="grid2 compact-grid">
                <div className="rounded-xl border border-white/10 bg-black/10 p-3 text-sm">
                  <div className="text-xs uppercase tracking-wider text-slate-400">Parent</div>
                  <p className="mt-1 font-semibold">{activeTask.parentName}</p>
                  <p className="text-slate-400">{activeTask.parentEmail}</p>
                </div>
                <div className="rounded-xl border border-white/10 bg-black/10 p-3 text-sm">
                  <div className="text-xs uppercase tracking-wider text-slate-400">Task Type</div>
                  <p className="mt-1 font-semibold">{activeTask.taskType}</p>
                  <p className="text-slate-400">{getPhase(activeTask.triggerLesson)}</p>
                </div>
              </div>
              <div className="rounded-xl border border-white/10 bg-black/10 p-3 text-sm">
                <div className="text-xs uppercase tracking-wider text-slate-400">Email Draft (Editable)</div>
                <p className="mt-2">
                  Hi {activeTask.parentName.split(" ")[0]}, we are following up on {activeTask.studentName}&apos;s lesson{" "}
                  {activeTask.triggerLesson} milestone. We&apos;ll share next steps shortly.
                </p>
              </div>
              <div className="flex justify-end gap-2">
                <button type="button" className="btn btn-sm" onClick={() => setActiveTask(null)}>
                  Cancel
                </button>
                <button type="button" className="btn btn-primary btn-sm" onClick={() => markComplete(activeTask.taskId)}>
                  Mark Complete
                </button>
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </section>
  );
}
